### ISSUE TITLE
New official dokku role

### ISSUE THREAD

**Issue by josegonzalez** [jalcine/ansible-role-dokku#1]
I just released an official Ansible role which contains quite a few modules for interacting with the actual Dokku installation. Please check it out here: https://github.com/dokku/ansible-dokku

Feel free to close this issue at your leisure.

**Comment by jalcine** [comment]
Ooh, this is nice! I’ll archive this project.

(Originally published at: https://v2.jacky.wtf/post/4853e4c0-22ff-4b44-95cd-d931ab795142)
